import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import ReactMarkdown from "react-markdown";

import styles from "../../styles/Main.module.css";

export default function Blog(props) {
  const [blog, setBlog] = useState(props.blog);

  return (
    <div className={styles.container}>
      <Head>
        <title>{blog.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.blog_container}>
        <h1 className={styles.title}>{blog.title}</h1>
        <hr />
        <p>
          <i>{blog.date}</i>
        </p>

        <div className={styles.content}>
          <ReactMarkdown>{blog.content}</ReactMarkdown>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const blog = (
    await axios.get(`http://localhost:3000/api/blog?slug=${context.query.slug}`)
  ).data;

  return {
    props: { blog },
  };
}
